[DEFAULT]
debian-branch = ubuntu-tab-x910-7.0
debian-tag = ubuntu-tab/x910-%(version)s
upstream-tag = upstream/%(version)s
upstream-branch = linux-7.0.y
upstream-vcs-tag = v%(version)s
pristine-tar = false

[dch]
commit-msg = d/changelog: release version %(version)s
